### ISSUE TITLE
How to use it with CRA?

### ISSUE THREAD

**Issue by athaylean** [coderas/babel-plugin-jsx-remove-data-test-id#12]
Hi! Is there any way to use it with Create React App without ejecting? If not can you add support for babel plugin macros? https://github.com/kentcdodds/babel-plugin-macros

**Comment by coderas** [comment]
Hi @athaylean - Thanks for the request, if you like, you can create a PR ? I think it's a good idea, I'm just not sure then I next have enough time to do this.

**Comment by alyssamuu** [comment]
You can use this with: https://github.com/arackaf/customize-cra

In your config-overrides.js:
`...addBabelPlugins('jsx-remove-data-test-id')`

**Comment by coderas** [comment]
Closing, though may reopen to do the work if there is enough appetite,
