### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by rezof** [coderas/babel-plugin-jsx-remove-data-test-id#13]
i have an implementation question.
is there a reason for visiting `JSXOpeningElement ` and iterate/validate all the attributes when you can visit `JSXAttribute` and do a quick match and remove ?

**Comment by coderas** [comment]
It was a while ago when I wrote this code, I can't remember exactly but I have a feeling the tests fail.

I'l give it a go later and if I find anything, I'll post it.

**Comment by coderas** [comment]
I think this is a good shout, I'll give it a go, cheers
