### ISSUE TITLE
Is there a way to remove data-* from .js files?

### ISSUE THREAD

**Issue by viniciusavieira** [coderas/babel-plugin-jsx-remove-data-test-id#14]
Hello and thanks for the plugin.

I was wondering, I'm working on a project where the files are actually .js instead of .jsx.

Could be possible to execute the same operation in .js files?

Thanks in advance.

**Comment by coderas** [comment]
Hi, this should be down to you build configuration. The plugin doesn't really care about the file extension, so anytime babel is parsing your JSX, it should strip the attributes just fine.

**Comment by viniciusavieira** [comment]
Nice, maybe I've got some setup wrong, I've installed the plugin and checked it really stripped off the data-testis(react-testing-library) but as I ran than test suite, it broke most of tests by not find this same data-testid elements.
Do I have to setup something different?
I did installed it and add to the plugin list on Babel.rc.

Thanks again.

**Comment by coderas** [comment]
Do you have some config to look at?

**Comment by coderas** [comment]
Do you have some config to look at?

Reopening, closed by accident!

**Comment by coderas** [comment]
closing, decided to go ahead and do this work.

**Comment by coderas** [comment]
It sounds a lot like you need a different setup for your test environment.

If you post your configs that might help us to take a look.

**Comment by jenniferlynparsons** [comment]
@viniciusavieira i had the same issue. i resolved it by limiting the plugin to the prod or dev environments only:
```javascript
{
  env: {
    production: {
      plugins: ["babel-plugin-jsx-remove-data-test-id"]
    },
    test: {
      plugins: ["other-plugins"]
    }
  }
}
```

**Comment by viniciusavieira** [comment]
@coderas sorry for the time without response. I think that actually what @jenniferlynparsons pointed makes a lot of sense, and I noticed that in the last release it is working fine.

It was probably related to the setup I guess.

Thanks for your time!

**Comment by coderas** [comment]
No worries, thanks for the thread!
