### ISSUE TITLE
Readme doesn't give full picture of config requirements

### ISSUE THREAD

**Issue by jenniferlynparsons** [coderas/babel-plugin-jsx-remove-data-test-id#15]
Just set this up and it's great. Only issue I had was that this plugin needs to be in the production env declaration in the babel config otherwise in some testing setups it will remove the attribute and cause failing tests.

Happy to make a PR to the Readme if it would be helpful. I used this in my config to get it to work properly:

```
{ 
  "env": {
    "production": {
      "plugins": ["babel-plugin-jsx-remove-data-test-id"]
    }
  }
}
```

**Comment by coderas** [comment]
Yes please, we'd welcome that.

Thanks for your feedback too.
