### ISSUE TITLE
Error | Cannot read property 'expression' of null

### ISSUE THREAD

**Issue by GoPro16** [coderas/babel-plugin-jsx-remove-data-test-id#26]
Caused By:
https://github.com/coderas/babel-plugin-jsx-remove-data-test-id/blob/master/src/index.js#L72-L74

If `value` is `null` it will not hit the default assignment to `{}` which causes the error: 
```
Cannot read property 'expression' of  @null
```

Fails When an element with a boolean attribute exists
```jsx
<Hello someBoolean />
```

**Comment by coderas** [comment]
@GoPro16 Thanks for the issue, if you can add this test case to the PR (maybe I missed something) that'd be useful.
