### ISSUE TITLE
Cannot read property value of undefined

### ISSUE THREAD

**Issue by GoPro16** [coderas/babel-plugin-jsx-remove-data-test-id#31]
Offender: https://github.com/coderas/babel-plugin-jsx-remove-data-test-id/blob/7581d228d4ddd319c49a4720986c9d8ecbcb94f4/src/index.js#L76

I am not familiar with all the babel-ness that happens under the hood here but it looks like there may be some edge case missing again.

Not to make this sound rash but I would strongly recommend possibly reverting master to `2.0.0` until the new version is stable. I am not sure how this isn't breaking other apps or maybe my company is the only one using this in production :smile:

Example Node That causes it.
This is the log of the `property` in the filter function on that line. `key` is not a property on this object which is leading to the type error.
```
Node {
  type: 'SpreadElement',
  start: 3998,
  end: 4009,
  loc:
   SourceLocation {
     start: Position { line: 135, column: 8 },
     end: Position { line: 135, column: 19 } },
  argument:
   Node {
     type: 'Identifier',
     start: 4001,
     end: 4009,
     loc:
      SourceLocation {
        start: [Position],
        end: [Position],
        identifierName: 'pageData' },
     name: 'pageData',
     leadingComments: undefined,
     innerComments: undefined,
     trailingComments: undefined },
  leadingComments: undefined,
  innerComments: undefined,
  trailingComments: undefined }
```

**Comment by mstruensee** [comment]
I have a quick fix for this, but to me its just a bandaid ... would need to look at spread expression to see if it can access the properties to see if they need to be removed ... can't seem to get a test to work though :( 

@coderas can you look at my branch and help with the test?
https://github.com/mstruensee/babel-plugin-jsx-remove-data-test-id/blob/bug/31/tests/remove-data-test-id.spec.js#L60

it keeps saying it cannot convert spread ... am I adding the plugin wrong based on how you "runTests" ?

**Comment by daggmano** [comment]
v2.0.1 seems okay in this regard.

**Comment by coderas** [comment]
@GoPro16 - I think you might be right, in this instance it may need a little more diligence before we roll forward on this.

@mstruensee, I'll take a look once we've gone back to `2.0.1`

**Comment by coderas** [comment]
I've been through and reverted the commits we have problems with, on top of this I think it's best if we can gather a few more edge cases and get this feature in with enough 👀 

I'm not usually once for winding back, but I think in this cases we don't yet know what we don't know. I'll take a look at this test in a couple of hours when I get to work.
