### ISSUE TITLE
It cannot detect attributes passed as properties

### ISSUE THREAD

**Issue by jonamat** [coderas/babel-plugin-jsx-remove-data-test-id#39]
If I pass a data-testid attribute as property into an object, the plugin seems not recognize it.

```js
<TextField
       inputProps={{
         ...params.inputProps,
         'data-testid': 'search-field',
         id: 'Autocomplete',
       }}
/>
```
Becomes in the build:
```js
{"data-testid":"search-field",id:"Autocomplete"}
```

**Comment by coderas** [comment]
This is a great feature request, we have had an attempt at this before but all efforts fell by the wayside.

It's not currently configured to work this, but if you want to develop this feature or anyone wants to pick this up then I'm all up for it.

**Comment by coderas** [comment]
@jonamat - Sorry I missed the PR, will take a look
