### ISSUE TITLE
Strip any attribute. Not only "data-test-id"

### ISSUE THREAD

**Issue by pksjce** [coderas/babel-plugin-jsx-remove-data-test-id#6]
I see that https://github.com/coderas/babel-plugin-jsx-remove-qa used to have support to remove arbitrary attributes as defined in .babelrc. Why not provide similar functionality in this plugin too?

**Comment by coderas** [comment]
Thanks for the issue, I did agonise about removing this. I believe the value of this plugin is party down to the uniformity and purpose (in other words the focussed nature of it). 

I'm not 100% concerned about that, if you want to drop a PR, maybe we can change it.

**Comment by chrkhl** [comment]
I created a pull request #8 for this issue, maybe you like it.
