### ISSUE TITLE
How can we do this only in production using Webpack?

### ISSUE THREAD

**Issue by Ram-SR** [coderas/babel-plugin-jsx-remove-data-test-id#7]

**Comment by coderas** [comment]
Thanks for this issue, I will update the docs soon.

**Comment by Silom** [comment]
We have different themes for Webpack configs in which we add or override things we want differently in certain environments.

**Comment by coderas** [comment]
makes sense to close the issue since this a babel config concern really. please let me know if still struggling and I'll ping you some examples I have.
